### ISSUE TITLE
CFF deployment error

### ISSUE THREAD

**Issue by dciangot** [hvanhaev/CommonFSQFramework#18]
Hi,

I was trying to compile CFF when I found so issues related to some files added/modified few patches ago.

In particular it was unable to compile HFRecHitView.cc (1) and EcalRecHitView.cc(2). 
Once I removed them everything proceeded well.

Cheers,
Diego

(1)

> > Compiling  /afs/cern.ch/user/d/dciangot/CMSSW_7_4_1_patch1/src/CommonFSQFramework_test/Core/src/JetView.cc 
> > /afs/cern.ch/user/d/dciangot/CMSSW_7_4_1_patch1/src/CommonFSQFramework_test/Core/src/HFRecHitView.cc: In member function 'virtual void HFRecHitView::fillSpecific(const edm::Event&, const edm::EventSetup&)':
> > /afs/cern.ch/user/d/dciangot/CMSSW_7_4_1_patch1/src/CommonFSQFramework_test/Core/src/HFRecHitView.cc:21:12: error: invalid use of incomplete type 'const class edm::EventSetup'
> >       iSetup.get < HcalDbRecord > ().get(conditions);

(2)

> > Compiling  /afs/cern.ch/user/d/dciangot/CMSSW_7_4_1_patch1/src/CommonFSQFramework_test/Core/src/EventIdData.cc 
> > /afs/cern.ch/user/d/dciangot/CMSSW_7_4_1_patch1/src/CommonFSQFramework_test/Core/src/EcalRecHitView.cc:1:62: fatal error: CommonFSQFramework/Core/interface/EcalRecHitView.h: No such file or directory
> >  #include "CommonFSQFramework/Core/interface/EcalRecHitView.h"
> >                                                               ^
> > compilation terminated.
> > /afs/cern.ch/user/d/dciangot/CMSSW_7_4_1_patch1/src/CommonFSQFramework_test/Core/src/EcalRecHitView.cc:1:62: fatal error: CommonFSQFramework/Core/interface/EcalRecHitView.h: No such file or directory
> >  #include "CommonFSQFramework/Core/interface/EcalRecHitView.h"

**Comment by hvanhaev** [comment]
Hi Diego,

Hmmm, could it have something to do with the fact that you are working in a directory called CommonFSQFramework_test/ instead of just CommonFramework?

I think there's a mismatch between versions, because he is looking for the header file EcalRecHitView.h in the normal CommonFSQFramework/Core/interface directory, but is it there? Or in CommonFSQFramework_test/Core/interface?

I would avoid to rename the directory, and work with different Git branches or so if you like to experiment...

Cheers,
Hans

**Comment by dciangot** [comment]
OK, i see.. Never mind then.

Diego
Il 19/giu/2015 15:38, "Hans Van Haevermaet" notifications@github.com ha
scritto:
